// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgpaeovhhfldeieuhvdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRncGFlb3ZoaGZsZGVpZXVodmRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDE4MzMsImV4cCI6MjA2NDYxNzgzM30.9unru9OwB2HmRCpip9KlJXKkiCzWJq5a71ID8V3ahE8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);